# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publishedDate', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('coverImage', models.CharField(max_length=300)),
                ('sortOrder', models.IntegerField()),
            ],
        ),
    ]
